Opcode = {0x0:{"code":"nop", "size":1, "format":"10x"},
          0x1:{"code":"move", "size":1, "format":"12x"},
          0x2:{"code":"move/from16", "size":2, "format":"22x"},
          0x3:{"code":"move/16", "size":3, "format":"32x"},
          0x4:{"code":"move-wide", "size":1, "format":"12x"},
          0x5:{"code":"move-wide/from16", "size":2, "format":"22x"},
          0x6:{"code":"move-wide/16", "size":3, "format":"32x"},
          0x7:{"code":"move-object", "size":1, "format":"12x"},
          0x8:{"code":"move-object/from16", "size":2, "format":"22x"},
          0x9:{"code":"move-object/16", "size":3, "format":"32x"},
          0xa:{"code":"move-result", "size":1, "format":"11x"},
          0xb:{"code":"move-result-wide", "size":1, "format":"11x"},
          0xc:{"code":"move-result-object", "size":1, "format":"11x"},
          0xd:{"code":"move-exception", "size":1, "format":"11x"},
          0xe:{"code":"return-void", "size":1, "format":"11x"},
          0xf:{"code":"return", "size":1, "format":"11x"},
          0x10:{"code":"return-wide", "size":1, "format":"11x"},
          0x11:{"code":"return-object", "size":1, "format":"11x"},
          0x12:{"code":"const/4", "size":1, "format":"11n"},
          0x13:{"code":"const/16", "size":2, "format":"21s"},
          0x14:{"code":"const", "size":3, "format":"31i"},
          0x15:{"code":"const/high16", "size":2, "format":"21h"},
          0x16:{"code":"const-wide/16", "size":2, "format":"21s"},
          0x17:{"code":"const-wide/32", "size":3, "format":"31i"},
          0x18:{"code":"const-wide", "size":5, "format":"51l"},
          0x19:{"code":"const-wide/high16", "size":2, "format":"21h"},
          0x1a:{"code":"const-string", "size":2, "format":"21c"},
          0x1b:{"code":"const-string/jumbo", "size":3, "format":"31c"},
          0x1c:{"code":"const-class", "size":2, "format":"21c"},
          0x1d:{"code":"monitor-enter", "size":1, "format":"11x"},
          0x1e:{"code":"monitor-exit", "size":1, "format":"11x"},
          0x1f:{"code":"check-cast", "size":2, "format":"21c"},
          0x20:{"code":"instance-of", "size":2, "format":"22c"},
          0x21:{"code":"array-length", "size":1, "format":"12x"},
          0x22:{"code":"new-instance", "size":2, "format":"21c"},
          0x23:{"code":"new-array", "size":2, "format":"22c"},
          0x24:{"code":"filled-new-array", "size":3, "format":"35c"},
          0x25:{"code":"filled-new-array/range", "size":3, "format":"3rc"},
          0x26:{"code":"fill-array-data", "size":3, "format":"31t"},
          0x27:{"code":"throw", "size":1, "format":"11x"},
          0x28:{"code":"goto", "size":1, "format":"10t"},
          0x29:{"code":"goto/16", "size":2, "format":"20t"},
          0x2a:{"code":"goto/32", "size":3, "format":"30t"},
          0x2b:{"code":"packed-switch", "size":3, "format":"31t"},
          0x2c:{"code":"sparse-switch", "size":3, "format":"31t"},
          0x2d:{"code":"cmpl-float", "size":2, "format":"23x"},
          0x2e:{"code":"cmpg-float", "size":2, "format":"23x"},
          0x2f:{"code":"cmpl-double", "size":2, "format":"23x"},
          0x30:{"code":"cmpg-double", "size":2, "format":"23x"},
          0x31:{"code":"cmp-long", "size":2, "format":"23x"},
          0x32:{"code":"if-eq", "size":2, "format":"22t"},
          0x33:{"code":"if-ne", "size":2, "format":"22t"},
          0x34:{"code":"if-lt", "size":2, "format":"22t"},
          0x35:{"code":"if-ge", "size":2, "format":"22t"},
          0x36:{"code":"if-gt", "size":2, "format":"22t"},
          0x37:{"code":"if-le", "size":2, "format":"22t"},
          0x38:{"code":"if-eqz", "size":2, "format":"21t"},
          0x39:{"code":"if-nez", "size":2, "format":"21t"},
          0x3a:{"code":"if-ltz", "size":2, "format":"21t"},
          0x3b:{"code":"if-gez", "size":2, "format":"21t"},
          0x3c:{"code":"if-gtz", "size":2, "format":"21t"},
          0x3d:{"code":"if-lez", "size":2, "format":"21t"},
          0x3e:{"code":"(unused)", "size":1, "format":"10x"},
          0x3f:{"code":"(unused)", "size":1, "format":"10x"},
          0x40:{"code":"(unused)", "size":1, "format":"10x"},
          0x41:{"code":"(unused)", "size":1, "format":"10x"},
          0x42:{"code":"(unused)", "size":1, "format":"10x"},
          0x43:{"code":"(unused)", "size":1, "format":"10x"},
          0x44:{"code":"aget", "size":2, "format":"23x"},
          0x45:{"code":"aget-wide", "size":2, "format":"23x"},
          0x46:{"code":"aget-object", "size":2, "format":"23x"},
          0x47:{"code":"aget-boolean", "size":2, "format":"23x"},
          0x48:{"code":"aget-byte", "size":2, "format":"23x"},
          0x49:{"code":"aget-char", "size":2, "format":"23x"},
          0x4a:{"code":"aget-short", "size":2, "format":"23x"},
          0x4b:{"code":"aput", "size":2, "format":"23x"},
          0x4c:{"code":"aput-wide", "size":2, "format":"23x"},
          0x4d:{"code":"aput-object", "size":2, "format":"23x"},
          0x4e:{"code":"aput-boolean", "size":2, "format":"23x"},
          0x4f:{"code":"aput-byte", "size":2, "format":"23x"},
          0x50:{"code":"aput-char", "size":2, "format":"23x"},
          0x51:{"code":"aput-short", "size":2, "format":"23x"},
          0x52:{"code":"iget", "size":2, "format":"22c"},
          0x53:{"code":"iget-wide", "size":2, "format":"22c"},
          0x54:{"code":"iget-object", "size":2, "format":"22c"},
          0x55:{"code":"iget-boolean", "size":2, "format":"22c"},
          0x56:{"code":"iget-byte", "size":2, "format":"22c"},
          0x57:{"code": "iget-char", "size":2, "format":"22c"},
          0x58:{"code": "iget-short", "size":2, "format":"22c"},
          0x59:{"code": "iput", "size":2, "format":"22c"},
          0x5a:{"code": "iput-wide", "size":2, "format":"22c"},
          0x5b:{"code": "iput-object", "size":2, "format":"22c"},
          0x5c:{"code": "iput-boolean", "size":2, "format":"22c"},
          0x5d:{"code": "iput-byte", "size":2, "format":"22c"},
          0x5e:{"code": "iput-char", "size":2, "format":"22c"},
          0x5f:{"code": "iput-short", "size":2, "format":"22c"},
          0x60:{"code": "sget", "size":2, "format":"21c"},
          0x61:{"code": "sget-wide", "size":2, "format":"21c"},
          0x62:{"code": "sget-object", "size":2, "format":"21c"},
          0x63:{"code": "sget-boolean", "size":2, "format":"21c"},
          0x64:{"code": "sget-byte", "size":2, "format":"21c"},
          0x65:{"code": "sget-char", "size":2, "format":"21c"},
          0x66:{"code": "sget-short", "size":2, "format":"21c"},
          0x67:{"code": "sput", "size":2, "format":"21c"},
          0x68:{"code": "sput-wide", "size":2, "format":"21c"},
          0x69:{"code": "sput-object", "size":2, "format":"21c"},
          0x6a:{"code": "sput-boolean", "size":2, "format":"21c"},
          0x6b:{"code": "sput-byte", "size":2, "format":"21c"},
          0x6c:{"code": "sput-char", "size":2, "format":"21c"},
          0x6d:{"code": "sput-short", "size":2, "format":"21c"},
          0x6e:{"code": "invoke-virtual", "size":3, "format":"35c"},
          0x6f:{"code": "invoke-super", "size":3, "format":"35c"},
          0x70:{"code": "invoke-direct", "size":3, "format":"35c"},
          0x71:{"code": "invoke-static", "size":3, "format":"35c"},
          0x72:{"code": "invoke-interface", "size":3, "format":"35c"},
          0x73:{"code":"(unused)", "size":1, "format":"10x"},
          0x74:{"code": "invoke-virtual/range", "size":3, "format":"3rc"},
          0x75:{"code": "invoke-super/range", "size":3, "format":"3rc"},
          0x76:{"code": "invoke-direct/range", "size":3, "format":"3rc"},
          0x77:{"code": "invoke-static/range", "size":3, "format":"3rc"},
          0x78:{"code": "invoke-interface/range", "size":3, "format":"3rc"},
          0x79:{"code": "(unused)", "size":1, "format":"10x"},
          0x7a:{"code": "(unused)", "size":1, "format":"10x"},
          0x7b:{"code": "neg-int", "size":1, "format":"12x"},
          0x7c:{"code": "not-int", "size":1, "format":"12x"},
          0x7d:{"code": "neg-long", "size":1, "format":"12x"},
          0x7e:{"code": "not-long", "size":1, "format":"12x"},
          0x7f:{"code": "neg-float", "size":1, "format":"12x"},
          0x80:{"code": "neg-double", "size":1, "format":"12x"},
          0x81:{"code": "int-to-long", "size":1, "format":"12x"},
          0x82:{"code": "int-to-float", "size":1, "format":"12x"},
          0x83:{"code": "int-to-double", "size":1, "format":"12x"},
          0x84:{"code": "long-to-int", "size":1, "format":"12x"},
          0x85:{"code": "long-to-float", "size":1, "format":"12x"},
          0x86:{"code": "long-to-double", "size":1, "format":"12x"},
          0x87:{"code": "float-to-int", "size":1, "format":"12x"},
          0x88:{"code": "float-to-long", "size":1, "format":"12x"},
          0x89:{"code": "float-to-double", "size":1, "format":"12x"},
          0x8a:{"code": "double-to-int", "size":1, "format":"12x"},
          0x8b:{"code": "double-to-long", "size":1, "format":"12x"},
          0x8c:{"code": "double-to-float", "size":1, "format":"12x"},
          0x8d:{"code": "int-to-byte", "size":1, "format":"12x"},
          0x8e:{"code": "int-to-char", "size":1, "format":"12x"},
          0x8f:{"code": "int-to-short", "size":1, "format":"12x"},
          0x90:{"code": "add-int", "size":2, "format":"23x"},
          0x91:{"code": "sub-int",  "size":2, "format":"23x"},
          0x92:{"code": "mul-int", "size":2, "format":"23x"},
          0x93:{"code": "div-int", "size":2, "format":"23x"},
          0x94:{"code": "rem-int", "size":2, "format":"23x"},
          0x95:{"code": "and-int", "size":2, "format":"23x"},
          0x96:{"code": "or-int", "size":2, "format":"23x"},
          0x97:{"code": "xor-int", "size":2, "format":"23x"},
          0x98:{"code": "shl-int", "size":2, "format":"23x"},
          0x99:{"code": "shr-int", "size":2, "format":"23x"},
          0x9a:{"code": "ushr-int", "size":2, "format":"23x"},
          0x9b:{"code": "add-long", "size":2, "format":"23x"},
          0x9c:{"code": "sub-long", "size":2, "format":"23x"},
          0x9d:{"code": "mul-long", "size":2, "format":"23x"},
          0x9e:{"code": "div-long", "size":2, "format":"23x"},
          0x9f:{"code": "rem-long", "size":2, "format":"23x"},
          0xa0:{"code": "and-long", "size":2, "format":"23x"},
          0xa1:{"code": "or-long", "size":2, "format":"23x"},
          0xa2:{"code": "xor-long", "size":2, "format":"23x"},
          0xa3:{"code": "shl-long", "size":2, "format":"23x"},
          0xa4:{"code": "shr-long", "size":2, "format":"23x"},
          0xa5:{"code": "ushr-long", "size":2, "format":"23x"},
          0xa6:{"code": "add-float", "size":2, "format":"23x"},
          0xa7:{"code": "sub-float", "size":2, "format":"23x"},
          0xa8:{"code": "mul-float", "size":2, "format":"23x"},
          0xa9:{"code": "div-float", "size":2, "format":"23x"},
          0xaa:{"code": "rem-float", "size":2, "format":"23x"},
          0xab:{"code": "add-double", "size":2, "format":"23x"},
          0xac:{"code": "sub-double", "size":2, "format":"23x"},
          0xad:{"code": "mul-double", "size":2, "format":"23x"},
          0xae:{"code": "div-double", "size":2, "format":"23x"},
          0xaf:{"code": "rem-double", "size":2, "format":"23x"},
          0xb0:{"code": "add-int/2addr", "size":1, "format":"12x"},
          0xb1:{"code": "sub-int/2addr",  "size":1, "format":"12x"},
          0xb2:{"code": "mul-int/2addr", "size":1, "format":"12x"},
          0xb3:{"code": "div-int/2addr", "size":1, "format":"12x"},
          0xb4:{"code": "rem-int/2addr", "size":1, "format":"12x"},
          0xb5:{"code": "and-int/2addr", "size":1, "format":"12x"},
          0xb6:{"code": "or-int/2addr", "size":1, "format":"12x"},
          0xb7:{"code": "xor-int/2addr", "size":1, "format":"12x"},
          0xb8:{"code": "shl-int/2addr", "size":1, "format":"12x"},
          0xb9:{"code": "shr-int/2addr", "size":1, "format":"12x"},
          0xba:{"code": "ushr-int/2addr", "size":1, "format":"12x"},
          0xbb:{"code": "add-long/2addr", "size":1, "format":"12x"},
          0xbc:{"code": "sub-long/2addr", "size":1, "format":"12x"},
          0xbd:{"code": "mul-long/2addr", "size":1, "format":"12x"},
          0xbe:{"code": "div-long/2addr", "size":1, "format":"12x"},
          0xbf:{"code": "rem-long/2addr", "size":1, "format":"12x"},
          0xc0:{"code": "and-long/2addr", "size":1, "format":"12x"},
          0xc1:{"code": "or-long/2addr", "size":1, "format":"12x"},
          0xc2:{"code": "xor-long/2addr", "size":1, "format":"12x"},
          0xc3:{"code": "shl-long/2addr", "size":1, "format":"12x"},
          0xc4:{"code": "shr-long/2addr", "size":1, "format":"12x"},
          0xc5:{"code": "ushr-long/2addr", "size":1, "format":"12x"},
          0xc6:{"code": "add-float/2addr", "size":1, "format":"12x"},
          0xc7:{"code": "sub-float/2addr", "size":1, "format":"12x"},
          0xc8:{"code": "mul-float/2addr", "size":1, "format":"12x"},
          0xc9:{"code": "div-float/2addr", "size":1, "format":"12x"},
          0xca:{"code": "rem-float/2addr", "size":1, "format":"12x"},
          0xcb:{"code": "add-double/2addr", "size":1, "format":"12x"},
          0xcc:{"code": "sub-double/2addr", "size":1, "format":"12x"},
          0xcd:{"code": "mul-double/2addr", "size":1, "format":"12x"},
          0xce:{"code": "div-double/2addr", "size":1, "format":"12x"},
          0xcf:{"code": "rem-double/2addr", "size":1, "format":"12x"},
          0xd0:{"code": "add-int/lit16", "size":2, "format":"22s"},
          0xd1:{"code": "rsub-int",  "size":2, "format":"22s"},
          0xd2:{"code": "mul-int/lit16", "size":2, "format":"22s"},
          0xd3:{"code": "div-int/lit16", "size":2, "format":"22s"},
          0xd4:{"code": "rem-int/lit16", "size":2, "format":"22s"},
          0xd5:{"code": "and-int/lit16", "size":2, "format":"22s"},
          0xd6:{"code": "or-int/lit16", "size":2, "format":"22s"},
          0xd7:{"code": "xor-int/lit16", "size":2, "format":"22s"},
          0xd8:{"code": "add-int/lit8", "size":2, "format":"22b"},
          0xd9:{"code": "rsub-int/lit8", "size":2, "format":"22b"},
          0xda:{"code": "mul-int/lit8", "size":2, "format":"22b"},
          0xdb:{"code": "div-int/lit8", "size":2, "format":"22b"},
          0xdc:{"code": "rem-int/lit8", "size":2, "format":"22b"},
          0xdd:{"code": "and-int/lit8", "size":2, "format":"22b"},
          0xde:{"code": "or-int/lit8", "size":2, "format":"22b"},
          0xdf:{"code": "xor-int/lit8", "size":2, "format":"22b"},
          0xe0:{"code": "shl-int/lit8", "size":2, "format":"22b"},
          0xe1:{"code": "shr-int/lit8", "size":2, "format":"22b"},
          0xe2:{"code": "ushr-int/lit8", "size":2, "format":"22b"},
          0xe3:{"code": "(unused)", "size":1, "format":"10x"},
          0xe4:{"code": "(unused)", "size":1, "format":"10x"},
          0xe5:{"code": "(unused)", "size":1, "format":"10x"},
          0xe6:{"code": "(unused)", "size":1, "format":"10x"},
          0xe7:{"code": "(unused)", "size":1, "format":"10x"},
          0xe8:{"code": "(unused)", "size":1, "format":"10x"},
          0xe9:{"code": "(unused)", "size":1, "format":"10x"},
          0xea:{"code": "(unused)", "size":1, "format":"10x"},
          0xeb:{"code": "(unused)", "size":1, "format":"10x"},
          0xec:{"code": "(unused)", "size":1, "format":"10x"},
          0xed:{"code": "(unused)", "size":1, "format":"10x"},
          0xee:{"code": "(unused)", "size":1, "format":"10x"},
          0xef:{"code": "(unused)", "size":1, "format":"10x"},
          0xf0:{"code": "(unused)", "size":1, "format":"10x"},
          0xf1:{"code": "(unused)", "size":1, "format":"10x"},
          0xf2:{"code": "(unused)", "size":1, "format":"10x"},
          0xf3:{"code": "(unused)", "size":1, "format":"10x"},
          0xf4:{"code": "(unused)", "size":1, "format":"10x"},
          0xf5:{"code": "(unused)", "size":1, "format":"10x"},
          0xf6:{"code": "(unused)", "size":1, "format":"10x"},
          0xf7:{"code": "(unused)", "size":1, "format":"10x"},
          0xf8:{"code": "(unused)", "size":1, "format":"10x"},
          0xf9:{"code": "(unused)", "size":1, "format":"10x"},
          0xfa:{"code": "invoke-polymorphic", "size":4, "format":"45cc"},
          0xfb:{"code": "invoke-polymorphic/range", "size":4, "format":"4rcc"},
          0xfc:{"code": "invoke-custom", "size":3, "format":"35c"},
          0xfd:{"code": "invoke-custom/range", "size":3, "format":"3rc"},
          0xfe:{"code": "(unused)", "size":1, "format":"10x"},
          0xff:{"code": "(unused)", "size":1, "format":"10x"}
}